# Configs for felipetorresvanegas.github.io

title: "felipetorresvanegas.github.io"
name: "Felipe Torres-Vanegas"
email: luisfelipe.torres@mail.utoronto.ca
url: "https://felipetorresvanegas.github.io"
repository: "felipetorresvanegas.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Felipe Torres-Vanegas"
  avatar : "/assets/images/headshot.jpg"
  bio    : "PhD Candidate<br>Department of Ecology & Evolutionary Biology<br>University of Toronto"
  location: "Toronto, Canada"
  github : felipetorresvanegas
  email  : luisfelipe.torres@mail.utoronto.ca
  orcid: "https://orcid.org/0000-0003-3093-3701"
  links:
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: https://scholar.google.com/citations?user=imtwcOMAAAAJ&hl=es
#    - label: "ORCID"
#      icon: "fab fa-fw fa-orcid"
#      url: "https://orcid.org/0000-0003-3093-3701"
#    - label: "researchgate"
#      icon: "fab fa-researchgate"
#      url: "https://www.researchgate.net/profile/Felipe_Torres-Vanegas"

# # comments by disqus
#comments:
#  provider: "disqus"
#  disqus:
#    shortname: ""

analytics:
  provider: "google"
  google:
    tracking_id: "UA-187651831-1"


# pagination for blog page
#paginate: 10 # number of posts to show
#paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
