---
- id: Torres-Vanegas_2021
  authors: __Felipe Torres-Vanegas__, Adam S. Hadley, Urs G. Kormann, F. Andrew Jones, Matthew G. Betts, Helene H. Wagner.
  title: "Pollinator foraging tactics have divergent consequences for the mating system of a tropical plant"
  # journal:
  year: Resubmitted to New Phytologist (NPH-MS-2021-38691.R1)
  # volume: 109
  # pages: 1730-1746
  # openaccess: false
  # pdf-url: https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2745.13594
  # data-url: https://datadryad.org/stash/dataset/doi:10.5061/dryad.rfj6q578w
  # github: https://github.com/felipetorresvanegas/pollinator_community
---
