---
- id: Torres-Vanegas_2025
  authors: Kathryn E.C. Davis, Emil Sloth Thomassen, Helene H. Wagner, Urs G. Kormann, Adam S. Hadley, Matthew G. Betts, __Felipe Torres-Vanegas__.
  title: "Incorporating pollinator movement into connectivity models predicts pollen-mediated gene flow and highlights the importance of regenerating forests in tropical landscapes."
  journal: Submitted.
  year: 2025
  # volume: 109
  # pages: 1730-1746
  # openaccess: false
  # pdf-url: https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2745.13594
  # data-url: https://datadryad.org/stash/dataset/doi:10.5061/dryad.rfj6q578w
  # github: https://github.com/felipetorresvanegas/pollinator_community

# - id: Torres-Vanegas_2023
  # authors: Øystein H. Opedal, Bastien Serre, Vanda Temesvári, Yedra García, Magne Friberg, __Felipe Torres-Vanegas__.
  # title: "Effects of nectar robbing on floral evolution in a pollination-generalized plant."
  #journal: In Review.
  # year: 2024
  # volume: 109
  # pages: 1730-1746
  # openaccess: false
  # pdf-url: https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2745.13594
  # data-url: https://datadryad.org/stash/dataset/doi:10.5061/dryad.rfj6q578w
  # github: https://github.com/felipetorresvanegas/pollinator_community

# - # id: Torres-Vanegas_2022
  # authors: __Felipe Torres-Vanegas__, Adam S. Hadley, Urs G. Kormann, F. Andrew Jones, Matthew G. Betts, Helene H. Wagner.
  # title: "Pollinator foraging tactics have divergent consequences for the mating system of a tropical plant"
  # journal:
  # year: Accepted at New Phytologist (NPH-MS-2021-38691.R1)
  # volume: 109
  # pages: 1730-1746
  # openaccess: false
  # pdf-url: https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2745.13594
  # data-url: https://datadryad.org/stash/dataset/doi:10.5061/dryad.rfj6q578w
  # github: https://github.com/felipetorresvanegas/pollinator_community
---
